from __future__ import annotations

import pytest


_LIVE_DOTENV_KEYS = {
    "ORACLE_DASHBOARD_TOKEN",
    "XAUEX_MANUAL_COMMAND_SECRET",
    "XAUEX_EVENT_JOURNAL_PATH",
    "XAUEX_SIGNAL_DIRECTIONAL_STATE_PATH",
    "QDRANT_ENABLED",
    "QDRANT_LOCATION",
    "QDRANT_PATH",
    "QDRANT_URL",
    "QDRANT_HOST",
    "QDRANT_API_KEY",
    "QDRANT_COLLECTION",
    "QDRANT_PREFIX",
    "QDRANT_TIMEOUT_SECONDS",
    "QDRANT_PORT",
    "QDRANT_GRPC_PORT",
    "QDRANT_PREFER_GRPC",
    "QDRANT_HTTPS",
    "QDRANT_FORCE_DISABLE_CHECK_SAME_THREAD",
    "QDRANT_CHECK_COMPATIBILITY",
    "XAUEX_SIGNAL_QDRANT_ENABLED",
    "XAUEX_SIGNAL_QDRANT_LOCATION",
    "XAUEX_SIGNAL_QDRANT_PATH",
    "XAUEX_SIGNAL_QDRANT_URL",
    "XAUEX_SIGNAL_QDRANT_HOST",
    "XAUEX_SIGNAL_QDRANT_API_KEY",
    "XAUEX_SIGNAL_QDRANT_COLLECTION",
    "XAUEX_SIGNAL_QDRANT_PREFIX",
    "XAUEX_SIGNAL_QDRANT_TIMEOUT_SECONDS",
    "XAUEX_SIGNAL_QDRANT_PORT",
    "XAUEX_SIGNAL_QDRANT_GRPC_PORT",
    "XAUEX_SIGNAL_QDRANT_PREFER_GRPC",
    "XAUEX_SIGNAL_QDRANT_HTTPS",
    "XAUEX_SIGNAL_QDRANT_FORCE_DISABLE_CHECK_SAME_THREAD",
    "XAUEX_SIGNAL_QDRANT_CHECK_COMPATIBILITY",
}


@pytest.fixture(autouse=True)
def isolate_live_dotenv(monkeypatch):
    for key in _LIVE_DOTENV_KEYS:
        monkeypatch.delenv(key, raising=False)
