[advisories]
yanked = "deny"
unmaintained = "workspace"
unsound = "workspace"

[licenses]
allow = [
  "Apache-2.0",
  "BSD-3-Clause",
  "MIT",
  "Unicode-3.0",
  "Zlib",
]
confidence-threshold = 0.8
private = { ignore = true }
exceptions = []

[bans]
multiple-versions = "deny"
wildcards = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
